version: "3.7"

networks:
  app-tier:
    driver: bridge

services:
  api:
    container_name: poseidon-api
    image: "poseidon:latest"
    command: ["./app", "api"]
    environment:
      - POSTGRES_HOST=poseidon-postgresql
      - REDIS_ADDRESSES=poseidon-redis:6379
    ports:
      - "8080:8080"
    networks:
      - app-tier

  master:
    container_name: poseidon-master
    image: "poseidon:latest"
    depends_on:
      - api
    command: ["./app", "master"]
    environment:
      - POSTGRES_HOST=poseidon-postgresql
      - REDIS_ADDRESSES=poseidon-redis:6379
    networks:
      - app-tier

  worker:
    container_name: poseidon-worker
    image: "poseidon:latest"
    depends_on:
      - api
    command: ["./app", "worker"]
    environment:
      - POSTGRES_HOST=poseidon-postgresql
      - REDIS_ADDRESSES=poseidon-redis:6379
    networks:
      - app-tier
