version: "3.7"

networks:
  app-tier:
    driver: bridge

services:
  postgresql-test:
    container_name: poseidon-postgresql-test
    image: "postgres:15.3"
    environment:
      - POSTGRES_DB=poseidon
      - POSTGRES_USER=poseidon
      - POSTGRES_PASSWORD=123456
    ports:
      - "6432:5432"
    networks:
      - app-tier

  redis-test:
    container_name: poseidon-redis-test
    image: "redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "7379:6379"
    networks:
      - app-tier
